# This workflow will build and push all the docker images defined in this repository
# and push them to the docker registry if needed.
name: Build and Push Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # 00:00 every Saturday

jobs:
  generate_matrix:
    name: Generate matrix for Dockerfile
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set matrix for Dockerfile
        id: set-matrix
        run: |
          DOCKERFILES_JSON=$(ls *.dockerfile | sed 's/.dockerfile//' | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=matrix::${DOCKERFILES_JSON}"

  build_and_push:
    name: Build and Push Docker Image
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/dev:${{ matrix.dockerfile }}
